# ---------------------------------------------------
#                    About
#  Plugin: ChestLogger
#  Developed By:
#  Version:
#  Support:
# ---------------------------------------------------
#                     Messages
# ---------------------------------------------------

Messages:
  prefix: "[ChestLogger]"

# ---------------------------------------------------
#                     Whitelist
#     This whitelist allows blocks to be tracked
# ---------------------------------------------------

whitelist:
  block:
    - "chest"
    - "shulker_box"
    - "minecraft:red_shulker_box"
    - "minecraft:lime_shulker_box"
    - "minecraft:pink_shulker_box"
    - "minecraft:gray_shulker_box"
    - "minecraft:cyan_shulker_box"
    - "minecraft:blue_shulker_box"
    - "minecraft:white_shulker_box"
    - "minecraft:brown_shulker_box"
    - "minecraft:green_shulker_box"
    - "minecraft:black_shulker_box"
    - "minecraft:orange_shulker_box"
    - "minecraft:magenta_shulker_box"
    - "minecraft:yellow_shulker_box"
    - "minecraft:purple_shulker_box"
    - "minecraft:light_blue_shulker_box"
    - "minecraft:light_gray_shulker_box"
    - "minecraft:red_shulker_box"
    - "TRAPPED_CHEST"
    - "BARREL"
  logicBlock:
    - "HOPPER"
    - "HOPPER_MINECART"

# ---------------------------------------------------
#                      Blacklist
#  Items in this blacklist do not need to be tracked
# ---------------------------------------------------

blacklist:
  item:
    - "AIR" # Air can be tracked, but it is recommended to add air to the blacklist
