# ---------------------------------------------------
#                    About
#  Plugin: ChestLogger
#  Developed By:
#  Version:
#  Support:
# ---------------------------------------------------
#                     Messages
# ---------------------------------------------------

Messages:
  prefix: '[ChestLogger]'

# ---------------------------------------------------
#                     Whitelist
#     This whitelist allows blocks to be tracked
# ---------------------------------------------------

whitelist:
  block:
    - chest
    - shulker_box
    - red_shulker_box
    - lime_shulker_box
    - pink_shulker_box
    - gray_shulker_box
    - cyan_shulker_box
    - blue_shulker_box
    - white_shulker_box
    - brown_shulker_box
    - green_shulker_box
    - black_shulker_box
    - orange_shulker_box
    - magenta_shulker_box
    - yellow_shulker_box
    - purple_shulker_box
    - light_blue_shulker_box
    - light_gray_shulker_box
    - red_shulker_box
    - trapped_chest
    - barrel
  logicBlock:
    - hopper
    - hopper_minecart

# ---------------------------------------------------
#                      Blacklist
#  Items in this blacklist do not need to be tracked
# ---------------------------------------------------

blacklist:
  item:
    - AIR
